### ISSUE TITLE
MSK Connect failing with - Unable to execute HTTP request: Connect to sts.amazonaws.com:443

### ISSUE THREAD

**Issue by mshidlov** [Nordstrom/kafka-connect-sqs#31]
I'm trying to set up MSK connect with SQS as a source and MSK as a sink.

I tried to use AssumeRole as described in the README.md example.
I created an IAM role `kafka-connect-sqs-role` and gave it to the MSK connect and set up the credentials properties and got `Unable to execute HTTP request: Connect to sts.amazonaws.com:443`.

### The credentials properties:
```
sqs.credentials.provider.session.name=my-kafka-connector-source-sqs-session
sqs.credentials.provider.role.arn=arn:aws:iam::<ACCOUNT-ID>:role/kafka-connect-sqs-role
sqs.credentials.provider.external.id=my-queue-external-id
sqs.credentials.provider.class=com.nordstrom.kafka.connect.auth.AWSAssumeRoleCredentialsProvider
```
When I tried to remove the AssumeRole,  like explained issue #30, I got the same error only with SQS instead of STS (`Unable to execute HTTP request: Connect to sqs.amazonaws.com:443`)

## connect properties
```
connector.class=com.nordstrom.kafka.connect.sqs.SqsSourceConnector
sqs.wait.time.seconds=5
topics=event-via-sqs
tasks.max=3
sqs.credentials.provider.session.name=my-kafka-connector-source-sqs-session
sqs.max.messages=5
sqs.credentials.provider.role.arn=arn:aws:iam::<ACCOUNT-ID>:role/kafka-connect-sqs
sqs.queue.url=https://sqs.us-east-1.amazonaws.com/<ACCOUNT-ID>/matan-test-sqs.fifo
sqs.region=us-east-1
sqs.credentials.provider.external.id=my-queue-external-id
value.converter=org.apache.kafka.connect.storage.StringConverter
sqs.credentials.provider.class=com.nordstrom.kafka.connect.auth.AWSAssumeRoleCredentialsProvider
key.converter=org.apache.kafka.connect.storage.StringConverter
```
### MSK permissions:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "kafka-cluster:Connect",
                "kafka-cluster:DescribeCluster"
            ],
            "Resource": [
                "arn:aws:kafka:us-east-1:<ACCOUNT-ID>:cluster/matan-test-msk/7e6aa63b-3875-48ed-aad1-4d6c9fa7432d-22"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "kafka-cluster:*Topic*",
                "kafka-cluster:WriteData",
                "kafka-cluster:ReadData"
            ],
            "Resource": [
                "arn:aws:kafka:us-east-1:<ACCOUNT-ID>:topic/matan-test-msk/7e6aa63b-3875-48ed-aad1-4d6c9fa7432d-22/*"
            ]
        }
    ]
}
```
### SQS permissions:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "sqs:*"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```
### STS permissions:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "sts:*",
            "Resource": "*"
        }
    ]
}
```

## Exception log:
```
[Worker-0e2d8e6aecab5dfeb] [2022-07-21 07:56:47,598] ERROR [matan2|task-1] WorkerSourceTask{id=matan2-1} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:191)
[Worker-0e2d8e6aecab5dfeb] com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to sts.amazonaws.com:443 [sts.amazonaws.com/54.239.29.25] failed: connect timed out
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1219)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1165)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.doInvoke(AWSSecurityTokenServiceClient.java:1727)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1694)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1683)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.executeAssumeRole(AWSSecurityTokenServiceClient.java:532)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.assumeRole(AWSSecurityTokenServiceClient.java:501)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.auth.STSAssumeRoleSessionCredentialsProvider.newSession(STSAssumeRoleSessionCredentialsProvider.java:348)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.auth.STSAssumeRoleSessionCredentialsProvider.access$000(STSAssumeRoleSessionCredentialsProvider.java:44)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.auth.STSAssumeRoleSessionCredentialsProvider$1.call(STSAssumeRoleSessionCredentialsProvider.java:93)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.auth.STSAssumeRoleSessionCredentialsProvider$1.call(STSAssumeRoleSessionCredentialsProvider.java:90)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.auth.RefreshableTask.refreshValue(RefreshableTask.java:295)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.auth.RefreshableTask.blockingRefresh(RefreshableTask.java:251)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.auth.RefreshableTask.getValue(RefreshableTask.java:192)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.auth.STSAssumeRoleSessionCredentialsProvider.getCredentials(STSAssumeRoleSessionCredentialsProvider.java:320)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.auth.STSAssumeRoleSessionCredentialsProvider.getCredentials(STSAssumeRoleSessionCredentialsProvider.java:43)
[Worker-0e2d8e6aecab5dfeb] 	at com.nordstrom.kafka.connect.auth.AWSAssumeRoleCredentialsProvider.getCredentials(AWSAssumeRoleCredentialsProvider.java:43)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1269)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:845)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:794)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2329)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2296)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2285)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.services.sqs.AmazonSQSClient.executeReceiveMessage(AmazonSQSClient.java:1715)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.services.sqs.AmazonSQSClient.receiveMessage(AmazonSQSClient.java:1683)
[Worker-0e2d8e6aecab5dfeb] 	at com.nordstrom.kafka.connect.sqs.SqsClient.receive(SqsClient.java:116)
[Worker-0e2d8e6aecab5dfeb] 	at com.nordstrom.kafka.connect.sqs.SqsSourceConnectorTask.poll(SqsSourceConnectorTask.java:80)
[Worker-0e2d8e6aecab5dfeb] 	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:291)
[Worker-0e2d8e6aecab5dfeb] 	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:248)
[Worker-0e2d8e6aecab5dfeb] 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)
[Worker-0e2d8e6aecab5dfeb] 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:238)
[Worker-0e2d8e6aecab5dfeb] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[Worker-0e2d8e6aecab5dfeb] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[Worker-0e2d8e6aecab5dfeb] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[Worker-0e2d8e6aecab5dfeb] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[Worker-0e2d8e6aecab5dfeb] 	at java.base/java.lang.Thread.run(Thread.java:829)
[Worker-0e2d8e6aecab5dfeb] Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to sts.amazonaws.com:443 [sts.amazonaws.com/54.239.29.25] failed: connect timed out
[Worker-0e2d8e6aecab5dfeb] 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
[Worker-0e2d8e6aecab5dfeb] 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
[Worker-0e2d8e6aecab5dfeb] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[Worker-0e2d8e6aecab5dfeb] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[Worker-0e2d8e6aecab5dfeb] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Worker-0e2d8e6aecab5dfeb] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.conn.$Proxy42.connect(Unknown Source)
[Worker-0e2d8e6aecab5dfeb] 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
[Worker-0e2d8e6aecab5dfeb] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
[Worker-0e2d8e6aecab5dfeb] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
[Worker-0e2d8e6aecab5dfeb] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
[Worker-0e2d8e6aecab5dfeb] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
[Worker-0e2d8e6aecab5dfeb] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1346)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
[Worker-0e2d8e6aecab5dfeb] 	... 47 more
[Worker-0e2d8e6aecab5dfeb] Caused by: java.net.SocketTimeoutException: connect timed out
[Worker-0e2d8e6aecab5dfeb] 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
[Worker-0e2d8e6aecab5dfeb] 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
[Worker-0e2d8e6aecab5dfeb] 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
[Worker-0e2d8e6aecab5dfeb] 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
[Worker-0e2d8e6aecab5dfeb] 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[Worker-0e2d8e6aecab5dfeb] 	at java.base/java.net.Socket.connect(Socket.java:609)
[Worker-0e2d8e6aecab5dfeb] 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
[Worker-0e2d8e6aecab5dfeb] 	at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:142)
[Worker-0e2d8e6aecab5dfeb] 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
[Worker-0e2d8e6aecab5dfeb] 	... 63 more
```

**Comment by mshidlov** [comment]
Solved this issue.

The MSK cluster was on a private subnet without NAT, once I added a NAT to the subnet the connector worked and messages were passing from SQS to MSK.
