### ISSUE TITLE
Missing SQS_MESSAGE_ATTRIBUTE_PARTITION_KEY configuration in config def - SQS Source connector

### ISSUE THREAD

**Issue by aksinghgrd** [Nordstrom/kafka-connect-sqs#47]
`org.apache.kafka.common.config.ConfigException: Unknown configuration 'sqs.message.attributes.partition.key'
    at org.apache.kafka.common.config.AbstractConfig.get(AbstractConfig.java:162)
    at org.apache.kafka.common.config.AbstractConfig.getString(AbstractConfig.java:197)
    at com.nordstrom.kafka.connect.sqs.SqsConnectorConfig.<init>(SqsConnectorConfig.java:33)
    at com.nordstrom.kafka.connect.sqs.SqsSourceConnectorConfig.<init>(SqsSourceConnectorConfig.java:51)
    at com.nordstrom.kafka.connect.sqs.SqsSourceConnectorTask.start(SqsSourceConnectorTask.java:61)
    at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.initializeAndStart(AbstractWorkerSourceTask.java:277)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:227)`

Missing configuration for SQS_MESSAGE_ATTRIBUTE_PARTITION_KEY in class SqsSourceConnectorConfig while creating ConfigDef CONFIG_DEF

**Comment by davidkurutz-reddit** [comment]
Upvoting this -- same issue here -- code looks like sqs.message.attribute.partition.key was implemented in SinkConnector and in Config objects -- we are trying to use the source connector only and getting this error.

```
org.apache.kafka.common.config.ConfigException: Unknown configuration 'sqs.message.attributes.partition.key'
	at org.apache.kafka.common.config.AbstractConfig.get(AbstractConfig.java:162)
	at org.apache.kafka.common.config.AbstractConfig.getString(AbstractConfig.java:197)
	at com.nordstrom.kafka.connect.sqs.SqsConnectorConfig.<init>(SqsConnectorConfig.java:33)
	at com.nordstrom.kafka.connect.sqs.SqsSourceConnectorConfig.<init>(SqsSourceConnectorConfig.java:51)
	at com.nordstrom.kafka.connect.sqs.SqsSourceConnectorTask.start(SqsSourceConnectorTask.java:61)
```

**Comment by dylanmei** [comment]
Let us known whether release [v1.6.1](https://github.com/Nordstrom/kafka-connect-sqs/releases/tag/v1.6.1) resolves the issue.

**Comment by rejthy** [comment]
It does not work, because there is no config definition for key 'sqs.message.attributes.partition.key' in class [SqsSourceConnectorConfig.java](https://github.com/Nordstrom/kafka-connect-sqs/blob/master/src/main/java/com/nordstrom/kafka/connect/sqs/SqsSourceConnectorConfig.java)
